version: "3.9"
services:
  joinmarket:
    build: .
  bitcoin-node:
    container_name: "bitcoin-node"
    image: "lightweight-btc"
    ports:
      - "8332:8332"
    volumes:
      - "/home/domowy/Downloads/blockchain:/data"