version: "3.9"

volumes:
  authDir:

services:
  joinmarket:
    container_name: "joinmarket"
    build:
      context: "./"
      args:
        bitcoinCoreVersion: 23.0
    volumes:
      - "authDir:/auth"
    depends_on:
      - bitcoin-node
  bitcoin-node:
    container_name: "bitcoin-node"
    image: "thebitcoinprof/lightweight-bitcoin-node"
    ports:
      - "8332:8332"
    volumes:
      - "/home/domowy/Downloads/blockchain:/data"
      - "authDir:/auth"